### ISSUE TITLE
npm issues

### ISSUE THREAD

**Issue by MaherJendoubi** [lunit-io/frontend-components#2]
Hi,

I got the following error locally when I run npm i:

npm i
Error: Failed to replace env in config: ${NPM_LUNIT_TOKEN}
    at C:\Users\maher\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (C:\Users\maher\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:411:12)
    at parseField (C:\Users\maher\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:389:7)
    at C:\Users\maher\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (C:\Users\maher\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:328:23)
    at ConfigChain.addString (C:\Users\maher\AppData\Roaming\npm\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Users\maher\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:316:10)
    at C:\Users\maher\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:115:16
C:\Users\maher\AppData\Roaming\npm\node_modules\npm\lib\npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (C:\Users\maher\AppData\Roaming\npm\node_modules\npm\lib\npm.js:59:13)
    at process.errorHandler (C:\Users\maher\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:205:32)
    at process.emit (events.js:223:5)
    at process._fatalException (internal/process/execution.js:150:25)

**Comment by iamssen** [comment]
https://github.com/lunit-io/frontend-components/pull/1#issuecomment-576008127
